# Generated by Django 4.2.11 on 2024-03-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_user_profile_mobile_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="subject",
            field=models.CharField(default="None", max_length=20),
        ),
    ]
