# Generated by Django 4.2.11 on 2024-03-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0003_contactus_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="subject",
            field=models.CharField(default="None", max_length=200),
        ),
    ]
