# Generated by Django 4.2.11 on 2024-03-17 19:07

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="post_featured_pics/"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
